//go:build ignore

// Command generate-unicode-normalization writes the browser tables used to
// match the API's Unicode 15 NFKC and case-folding behavior exactly.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"unicode/utf8"

	"golang.org/x/text/cases"
	"golang.org/x/text/unicode/norm"
)

const outputPath = "apps/web/src/unicode-normalization.ts"

type stringMapping struct {
	input  string
	output string
}

type classMapping struct {
	input string
	class uint8
}

func quoted(value string) string {
	encoded, err := json.Marshal(value)
	if err != nil {
		panic(err)
	}
	return string(encoded)
}

func main() {
	decompositions := make([]stringMapping, 0, 6000)
	classes := make([]classMapping, 0, 1000)
	compositions := make([]stringMapping, 0, 1000)
	foldings := make([]stringMapping, 0, 1600)
	folder := cases.Fold()

	for codePoint := rune(0); codePoint <= utf8.MaxRune; codePoint++ {
		if codePoint >= 0xD800 && codePoint <= 0xDFFF {
			continue
		}
		input := string(codePoint)
		if decomposition := norm.NFKD.String(input); decomposition != input && (codePoint < 0xAC00 || codePoint > 0xD7A3) {
			decompositions = append(decompositions, stringMapping{input, decomposition})
		}
		if class := norm.NFD.PropertiesString(input).CCC(); class != 0 {
			classes = append(classes, classMapping{input, class})
		}
		if decomposition := []rune(norm.NFD.String(input)); len(decomposition) >= 2 && (codePoint < 0xAC00 || codePoint > 0xD7A3) {
			prefix := norm.NFC.String(string(decomposition[:len(decomposition)-1]))
			last := string(decomposition[len(decomposition)-1])
			if utf8.RuneCountInString(prefix) == 1 && norm.NFC.String(prefix+last) == input {
				compositions = append(compositions, stringMapping{prefix + last, input})
			}
		}
		if folded := folder.String(input); folded != input {
			foldings = append(foldings, stringMapping{input, folded})
		}
	}

	var output strings.Builder
	output.WriteString("// Generated by scripts/generate-unicode-normalization.go from golang.org/x/text v0.39.0.\n")
	output.WriteString("// Do not edit by hand. These Unicode 15 tables match the API normalization contract.\n")
	writeStringMap(&output, "compatibilityDecomposition", decompositions)
	writeClassMap(&output, classes)
	writeStringMap(&output, "canonicalComposition", compositions)
	writeStringMap(&output, "caseFolding", foldings)
	output.WriteString(normalizationImplementation)

	if err := os.WriteFile(outputPath, []byte(output.String()), 0o644); err != nil {
		panic(err)
	}
	fmt.Printf("wrote %s (%d decompositions, %d combining classes, %d compositions, %d foldings)\n", outputPath, len(decompositions), len(classes), len(compositions), len(foldings))
}

func writeStringMap(output *strings.Builder, name string, mappings []stringMapping) {
	fmt.Fprintf(output, "\nconst %s = new Map<string, string>([\n", name)
	for _, mapping := range mappings {
		fmt.Fprintf(output, "  [%s, %s],\n", quoted(mapping.input), quoted(mapping.output))
	}
	output.WriteString("]);\n")
}

func writeClassMap(output *strings.Builder, mappings []classMapping) {
	output.WriteString("\nconst canonicalCombiningClass = new Map<string, number>([\n")
	for _, mapping := range mappings {
		fmt.Fprintf(output, "  [%s, %d],\n", quoted(mapping.input), mapping.class)
	}
	output.WriteString("]);\n")
}

const normalizationImplementation = `
const hangulBase = 0xac00;
const hangulLast = 0xd7a3;
const leadingJamoBase = 0x1100;
const leadingJamoCount = 19;
const vowelJamoBase = 0x1161;
const vowelJamoCount = 21;
const trailingJamoBase = 0x11a7;
const trailingJamoCount = 28;

function composeHangul(starter: string, next: string) {
  const starterPoint = starter.codePointAt(0)!;
  const nextPoint = next.codePointAt(0)!;
  if (starterPoint >= leadingJamoBase && starterPoint < leadingJamoBase + leadingJamoCount
      && nextPoint >= vowelJamoBase && nextPoint < vowelJamoBase + vowelJamoCount) {
    const syllable = hangulBase + ((starterPoint - leadingJamoBase) * vowelJamoCount + nextPoint - vowelJamoBase) * trailingJamoCount;
    return String.fromCodePoint(syllable);
  }
  if (starterPoint >= hangulBase && starterPoint <= hangulLast && (starterPoint - hangulBase) % trailingJamoCount === 0
      && nextPoint > trailingJamoBase && nextPoint < trailingJamoBase + trailingJamoCount) {
    return String.fromCodePoint(starterPoint + nextPoint - trailingJamoBase);
  }
  return undefined;
}

function decomposeSymbol(symbol: string) {
  const codePoint = symbol.codePointAt(0)!;
  if (codePoint < hangulBase || codePoint > hangulLast) return compatibilityDecomposition.get(symbol) ?? symbol;
  const syllableIndex = codePoint - hangulBase;
  const leading = leadingJamoBase + Math.floor(syllableIndex / (vowelJamoCount * trailingJamoCount));
  const vowel = vowelJamoBase + Math.floor((syllableIndex % (vowelJamoCount * trailingJamoCount)) / trailingJamoCount);
  const trailing = syllableIndex % trailingJamoCount;
  return String.fromCodePoint(leading, vowel, ...(trailing ? [trailingJamoBase + trailing] : []));
}

export function normalizeUnicode15NFKC(value: string) {
  const characters = Array.from(value, decomposeSymbol).flatMap((value) => Array.from(value));
  for (let index = 1; index < characters.length; index += 1) {
    const currentClass = canonicalCombiningClass.get(characters[index]) ?? 0;
    if (currentClass === 0) continue;
    let position = index;
    while (position > 0) {
      const previousClass = canonicalCombiningClass.get(characters[position - 1]) ?? 0;
      if (previousClass === 0 || previousClass <= currentClass) break;
      [characters[position - 1], characters[position]] = [characters[position], characters[position - 1]];
      position -= 1;
    }
  }
  if (characters.length < 2) return characters.join("");

  let starterIndex = 0;
  let starter = characters[0];
  let previousClass = 0;
  for (let index = 1; index < characters.length;) {
    const next = characters[index];
    const nextClass = canonicalCombiningClass.get(next) ?? 0;
    const composite = composeHangul(starter, next) ?? canonicalComposition.get(starter + next);
    if (composite && (previousClass === 0 || previousClass < nextClass)) {
      characters[starterIndex] = composite;
      starter = composite;
      characters.splice(index, 1);
      continue;
    }
    if (nextClass === 0) {
      starterIndex = index;
      starter = next;
    }
    previousClass = nextClass;
    index += 1;
  }
  return characters.join("");
}

export function normalizeUnicode15Title(value: string) {
  return Array.from(normalizeUnicode15NFKC(value), (symbol) => caseFolding.get(symbol) ?? symbol).join("");
}
`
